//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Concesionario.ServiceReference1.HelloWorldResponse HelloWorld(Concesionario.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Concesionario.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento texto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar_numero", ReplyAction="*")]
        Concesionario.ServiceReference1.Validar_numeroResponse Validar_numero(Concesionario.ServiceReference1.Validar_numeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar_numero", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.Validar_numeroResponse> Validar_numeroAsync(Concesionario.ServiceReference1.Validar_numeroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Formulario", ReplyAction="*")]
        Concesionario.ServiceReference1.FormularioResponse Formulario(Concesionario.ServiceReference1.FormularioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Formulario", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.FormularioResponse> FormularioAsync(Concesionario.ServiceReference1.FormularioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Concesionario.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Concesionario.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_numeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_numero", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.Validar_numeroRequestBody Body;
        
        public Validar_numeroRequest() {
        }
        
        public Validar_numeroRequest(Concesionario.ServiceReference1.Validar_numeroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Validar_numeroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public Validar_numeroRequestBody() {
        }
        
        public Validar_numeroRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_numeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_numeroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.Validar_numeroResponseBody Body;
        
        public Validar_numeroResponse() {
        }
        
        public Validar_numeroResponse(Concesionario.ServiceReference1.Validar_numeroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Validar_numeroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Validar_numeroResult;
        
        public Validar_numeroResponseBody() {
        }
        
        public Validar_numeroResponseBody(string Validar_numeroResult) {
            this.Validar_numeroResult = Validar_numeroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormularioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Formulario", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.FormularioRequestBody Body;
        
        public FormularioRequest() {
        }
        
        public FormularioRequest(Concesionario.ServiceReference1.FormularioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormularioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        public FormularioRequestBody() {
        }
        
        public FormularioRequestBody(string placa, string marca, string modelo, string color) {
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormularioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FormularioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.FormularioResponseBody Body;
        
        public FormularioResponse() {
        }
        
        public FormularioResponse(Concesionario.ServiceReference1.FormularioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormularioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FormularioResult;
        
        public FormularioResponseBody() {
        }
        
        public FormularioResponseBody(string FormularioResult) {
            this.FormularioResult = FormularioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Concesionario.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Concesionario.ServiceReference1.WebService1Soap>, Concesionario.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.HelloWorldResponse Concesionario.ServiceReference1.WebService1Soap.HelloWorld(Concesionario.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Concesionario.ServiceReference1.HelloWorldRequest inValue = new Concesionario.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Concesionario.ServiceReference1.HelloWorldRequestBody();
            Concesionario.ServiceReference1.HelloWorldResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.HelloWorldResponse> Concesionario.ServiceReference1.WebService1Soap.HelloWorldAsync(Concesionario.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Concesionario.ServiceReference1.HelloWorldRequest inValue = new Concesionario.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Concesionario.ServiceReference1.HelloWorldRequestBody();
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.Validar_numeroResponse Concesionario.ServiceReference1.WebService1Soap.Validar_numero(Concesionario.ServiceReference1.Validar_numeroRequest request) {
            return base.Channel.Validar_numero(request);
        }
        
        public string Validar_numero(string texto) {
            Concesionario.ServiceReference1.Validar_numeroRequest inValue = new Concesionario.ServiceReference1.Validar_numeroRequest();
            inValue.Body = new Concesionario.ServiceReference1.Validar_numeroRequestBody();
            inValue.Body.texto = texto;
            Concesionario.ServiceReference1.Validar_numeroResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).Validar_numero(inValue);
            return retVal.Body.Validar_numeroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.Validar_numeroResponse> Concesionario.ServiceReference1.WebService1Soap.Validar_numeroAsync(Concesionario.ServiceReference1.Validar_numeroRequest request) {
            return base.Channel.Validar_numeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.Validar_numeroResponse> Validar_numeroAsync(string texto) {
            Concesionario.ServiceReference1.Validar_numeroRequest inValue = new Concesionario.ServiceReference1.Validar_numeroRequest();
            inValue.Body = new Concesionario.ServiceReference1.Validar_numeroRequestBody();
            inValue.Body.texto = texto;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).Validar_numeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.FormularioResponse Concesionario.ServiceReference1.WebService1Soap.Formulario(Concesionario.ServiceReference1.FormularioRequest request) {
            return base.Channel.Formulario(request);
        }
        
        public string Formulario(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.FormularioRequest inValue = new Concesionario.ServiceReference1.FormularioRequest();
            inValue.Body = new Concesionario.ServiceReference1.FormularioRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            Concesionario.ServiceReference1.FormularioResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).Formulario(inValue);
            return retVal.Body.FormularioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.FormularioResponse> Concesionario.ServiceReference1.WebService1Soap.FormularioAsync(Concesionario.ServiceReference1.FormularioRequest request) {
            return base.Channel.FormularioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.FormularioResponse> FormularioAsync(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.FormularioRequest inValue = new Concesionario.ServiceReference1.FormularioRequest();
            inValue.Body = new Concesionario.ServiceReference1.FormularioRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).FormularioAsync(inValue);
        }
    }
}
