//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CrearBaseDatosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearBaseDatos", ReplyAction="*")]
        Concesionario.ServiceReference1.CrearBaseDatosResponse CrearBaseDatos(Concesionario.ServiceReference1.CrearBaseDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearBaseDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.CrearBaseDatosResponse> CrearBaseDatosAsync(Concesionario.ServiceReference1.CrearBaseDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CrearTableResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTable", ReplyAction="*")]
        Concesionario.ServiceReference1.CrearTableResponse CrearTable(Concesionario.ServiceReference1.CrearTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTable", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.CrearTableResponse> CrearTableAsync(Concesionario.ServiceReference1.CrearTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAuto", ReplyAction="*")]
        Concesionario.ServiceReference1.SaveAutoResponse SaveAuto(Concesionario.ServiceReference1.SaveAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.SaveAutoResponse> SaveAutoAsync(Concesionario.ServiceReference1.SaveAutoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento criterioBusqueda del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAuto", ReplyAction="*")]
        Concesionario.ServiceReference1.BuscarAutoResponse BuscarAuto(Concesionario.ServiceReference1.BuscarAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.BuscarAutoResponse> BuscarAutoAsync(Concesionario.ServiceReference1.BuscarAutoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAuto", ReplyAction="*")]
        Concesionario.ServiceReference1.ActualizarAutoResponse ActualizarAuto(Concesionario.ServiceReference1.ActualizarAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.ActualizarAutoResponse> ActualizarAutoAsync(Concesionario.ServiceReference1.ActualizarAutoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAuto", ReplyAction="*")]
        Concesionario.ServiceReference1.EliminarAutoResponse EliminarAuto(Concesionario.ServiceReference1.EliminarAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.EliminarAutoResponse> EliminarAutoAsync(Concesionario.ServiceReference1.EliminarAutoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Concesionario.ServiceReference1.HelloWorldResponse HelloWorld(Concesionario.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Concesionario.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento texto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar_numero", ReplyAction="*")]
        Concesionario.ServiceReference1.Validar_numeroResponse Validar_numero(Concesionario.ServiceReference1.Validar_numeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar_numero", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.Validar_numeroResponse> Validar_numeroAsync(Concesionario.ServiceReference1.Validar_numeroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento placa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Formulario", ReplyAction="*")]
        Concesionario.ServiceReference1.FormularioResponse Formulario(Concesionario.ServiceReference1.FormularioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Formulario", ReplyAction="*")]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.FormularioResponse> FormularioAsync(Concesionario.ServiceReference1.FormularioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearBaseDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearBaseDatos", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.CrearBaseDatosRequestBody Body;
        
        public CrearBaseDatosRequest() {
        }
        
        public CrearBaseDatosRequest(Concesionario.ServiceReference1.CrearBaseDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CrearBaseDatosRequestBody {
        
        public CrearBaseDatosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearBaseDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearBaseDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.CrearBaseDatosResponseBody Body;
        
        public CrearBaseDatosResponse() {
        }
        
        public CrearBaseDatosResponse(Concesionario.ServiceReference1.CrearBaseDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearBaseDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CrearBaseDatosResult;
        
        public CrearBaseDatosResponseBody() {
        }
        
        public CrearBaseDatosResponseBody(string CrearBaseDatosResult) {
            this.CrearBaseDatosResult = CrearBaseDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTable", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.CrearTableRequestBody Body;
        
        public CrearTableRequest() {
        }
        
        public CrearTableRequest(Concesionario.ServiceReference1.CrearTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CrearTableRequestBody {
        
        public CrearTableRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.CrearTableResponseBody Body;
        
        public CrearTableResponse() {
        }
        
        public CrearTableResponse(Concesionario.ServiceReference1.CrearTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CrearTableResult;
        
        public CrearTableResponseBody() {
        }
        
        public CrearTableResponseBody(string CrearTableResult) {
            this.CrearTableResult = CrearTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAuto", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.SaveAutoRequestBody Body;
        
        public SaveAutoRequest() {
        }
        
        public SaveAutoRequest(Concesionario.ServiceReference1.SaveAutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        public SaveAutoRequestBody() {
        }
        
        public SaveAutoRequestBody(string placa, string marca, string modelo, string color) {
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.SaveAutoResponseBody Body;
        
        public SaveAutoResponse() {
        }
        
        public SaveAutoResponse(Concesionario.ServiceReference1.SaveAutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveAutoResult;
        
        public SaveAutoResponseBody() {
        }
        
        public SaveAutoResponseBody(string SaveAutoResult) {
            this.SaveAutoResult = SaveAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAuto", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.BuscarAutoRequestBody Body;
        
        public BuscarAutoRequest() {
        }
        
        public BuscarAutoRequest(Concesionario.ServiceReference1.BuscarAutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarAutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string criterioBusqueda;
        
        public BuscarAutoRequestBody() {
        }
        
        public BuscarAutoRequestBody(string criterioBusqueda) {
            this.criterioBusqueda = criterioBusqueda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.BuscarAutoResponseBody Body;
        
        public BuscarAutoResponse() {
        }
        
        public BuscarAutoResponse(Concesionario.ServiceReference1.BuscarAutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarAutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarAutoResult;
        
        public BuscarAutoResponseBody() {
        }
        
        public BuscarAutoResponseBody(string BuscarAutoResult) {
            this.BuscarAutoResult = BuscarAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarAutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarAuto", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.ActualizarAutoRequestBody Body;
        
        public ActualizarAutoRequest() {
        }
        
        public ActualizarAutoRequest(Concesionario.ServiceReference1.ActualizarAutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarAutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        public ActualizarAutoRequestBody() {
        }
        
        public ActualizarAutoRequestBody(string placa, string marca, string modelo, string color) {
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarAutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarAutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.ActualizarAutoResponseBody Body;
        
        public ActualizarAutoResponse() {
        }
        
        public ActualizarAutoResponse(Concesionario.ServiceReference1.ActualizarAutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarAutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarAutoResult;
        
        public ActualizarAutoResponseBody() {
        }
        
        public ActualizarAutoResponseBody(string ActualizarAutoResult) {
            this.ActualizarAutoResult = ActualizarAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarAutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarAuto", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.EliminarAutoRequestBody Body;
        
        public EliminarAutoRequest() {
        }
        
        public EliminarAutoRequest(Concesionario.ServiceReference1.EliminarAutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarAutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        public EliminarAutoRequestBody() {
        }
        
        public EliminarAutoRequestBody(string placa) {
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarAutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarAutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.EliminarAutoResponseBody Body;
        
        public EliminarAutoResponse() {
        }
        
        public EliminarAutoResponse(Concesionario.ServiceReference1.EliminarAutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarAutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarAutoResult;
        
        public EliminarAutoResponseBody() {
        }
        
        public EliminarAutoResponseBody(string EliminarAutoResult) {
            this.EliminarAutoResult = EliminarAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Concesionario.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Concesionario.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_numeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_numero", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.Validar_numeroRequestBody Body;
        
        public Validar_numeroRequest() {
        }
        
        public Validar_numeroRequest(Concesionario.ServiceReference1.Validar_numeroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Validar_numeroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        public Validar_numeroRequestBody() {
        }
        
        public Validar_numeroRequestBody(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_numeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_numeroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.Validar_numeroResponseBody Body;
        
        public Validar_numeroResponse() {
        }
        
        public Validar_numeroResponse(Concesionario.ServiceReference1.Validar_numeroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Validar_numeroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Validar_numeroResult;
        
        public Validar_numeroResponseBody() {
        }
        
        public Validar_numeroResponseBody(bool Validar_numeroResult) {
            this.Validar_numeroResult = Validar_numeroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormularioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Formulario", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.FormularioRequestBody Body;
        
        public FormularioRequest() {
        }
        
        public FormularioRequest(Concesionario.ServiceReference1.FormularioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormularioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        public FormularioRequestBody() {
        }
        
        public FormularioRequestBody(string placa, string marca, string modelo, string color) {
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormularioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FormularioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concesionario.ServiceReference1.FormularioResponseBody Body;
        
        public FormularioResponse() {
        }
        
        public FormularioResponse(Concesionario.ServiceReference1.FormularioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormularioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FormularioResult;
        
        public FormularioResponseBody() {
        }
        
        public FormularioResponseBody(string FormularioResult) {
            this.FormularioResult = FormularioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Concesionario.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Concesionario.ServiceReference1.WebService1Soap>, Concesionario.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.CrearBaseDatosResponse Concesionario.ServiceReference1.WebService1Soap.CrearBaseDatos(Concesionario.ServiceReference1.CrearBaseDatosRequest request) {
            return base.Channel.CrearBaseDatos(request);
        }
        
        public string CrearBaseDatos() {
            Concesionario.ServiceReference1.CrearBaseDatosRequest inValue = new Concesionario.ServiceReference1.CrearBaseDatosRequest();
            inValue.Body = new Concesionario.ServiceReference1.CrearBaseDatosRequestBody();
            Concesionario.ServiceReference1.CrearBaseDatosResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).CrearBaseDatos(inValue);
            return retVal.Body.CrearBaseDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.CrearBaseDatosResponse> Concesionario.ServiceReference1.WebService1Soap.CrearBaseDatosAsync(Concesionario.ServiceReference1.CrearBaseDatosRequest request) {
            return base.Channel.CrearBaseDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.CrearBaseDatosResponse> CrearBaseDatosAsync() {
            Concesionario.ServiceReference1.CrearBaseDatosRequest inValue = new Concesionario.ServiceReference1.CrearBaseDatosRequest();
            inValue.Body = new Concesionario.ServiceReference1.CrearBaseDatosRequestBody();
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).CrearBaseDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.CrearTableResponse Concesionario.ServiceReference1.WebService1Soap.CrearTable(Concesionario.ServiceReference1.CrearTableRequest request) {
            return base.Channel.CrearTable(request);
        }
        
        public string CrearTable() {
            Concesionario.ServiceReference1.CrearTableRequest inValue = new Concesionario.ServiceReference1.CrearTableRequest();
            inValue.Body = new Concesionario.ServiceReference1.CrearTableRequestBody();
            Concesionario.ServiceReference1.CrearTableResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).CrearTable(inValue);
            return retVal.Body.CrearTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.CrearTableResponse> Concesionario.ServiceReference1.WebService1Soap.CrearTableAsync(Concesionario.ServiceReference1.CrearTableRequest request) {
            return base.Channel.CrearTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.CrearTableResponse> CrearTableAsync() {
            Concesionario.ServiceReference1.CrearTableRequest inValue = new Concesionario.ServiceReference1.CrearTableRequest();
            inValue.Body = new Concesionario.ServiceReference1.CrearTableRequestBody();
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).CrearTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.SaveAutoResponse Concesionario.ServiceReference1.WebService1Soap.SaveAuto(Concesionario.ServiceReference1.SaveAutoRequest request) {
            return base.Channel.SaveAuto(request);
        }
        
        public string SaveAuto(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.SaveAutoRequest inValue = new Concesionario.ServiceReference1.SaveAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.SaveAutoRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            Concesionario.ServiceReference1.SaveAutoResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).SaveAuto(inValue);
            return retVal.Body.SaveAutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.SaveAutoResponse> Concesionario.ServiceReference1.WebService1Soap.SaveAutoAsync(Concesionario.ServiceReference1.SaveAutoRequest request) {
            return base.Channel.SaveAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.SaveAutoResponse> SaveAutoAsync(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.SaveAutoRequest inValue = new Concesionario.ServiceReference1.SaveAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.SaveAutoRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).SaveAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.BuscarAutoResponse Concesionario.ServiceReference1.WebService1Soap.BuscarAuto(Concesionario.ServiceReference1.BuscarAutoRequest request) {
            return base.Channel.BuscarAuto(request);
        }
        
        public string BuscarAuto(string criterioBusqueda) {
            Concesionario.ServiceReference1.BuscarAutoRequest inValue = new Concesionario.ServiceReference1.BuscarAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.BuscarAutoRequestBody();
            inValue.Body.criterioBusqueda = criterioBusqueda;
            Concesionario.ServiceReference1.BuscarAutoResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).BuscarAuto(inValue);
            return retVal.Body.BuscarAutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.BuscarAutoResponse> Concesionario.ServiceReference1.WebService1Soap.BuscarAutoAsync(Concesionario.ServiceReference1.BuscarAutoRequest request) {
            return base.Channel.BuscarAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.BuscarAutoResponse> BuscarAutoAsync(string criterioBusqueda) {
            Concesionario.ServiceReference1.BuscarAutoRequest inValue = new Concesionario.ServiceReference1.BuscarAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.BuscarAutoRequestBody();
            inValue.Body.criterioBusqueda = criterioBusqueda;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).BuscarAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.ActualizarAutoResponse Concesionario.ServiceReference1.WebService1Soap.ActualizarAuto(Concesionario.ServiceReference1.ActualizarAutoRequest request) {
            return base.Channel.ActualizarAuto(request);
        }
        
        public string ActualizarAuto(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.ActualizarAutoRequest inValue = new Concesionario.ServiceReference1.ActualizarAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.ActualizarAutoRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            Concesionario.ServiceReference1.ActualizarAutoResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).ActualizarAuto(inValue);
            return retVal.Body.ActualizarAutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.ActualizarAutoResponse> Concesionario.ServiceReference1.WebService1Soap.ActualizarAutoAsync(Concesionario.ServiceReference1.ActualizarAutoRequest request) {
            return base.Channel.ActualizarAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.ActualizarAutoResponse> ActualizarAutoAsync(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.ActualizarAutoRequest inValue = new Concesionario.ServiceReference1.ActualizarAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.ActualizarAutoRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).ActualizarAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.EliminarAutoResponse Concesionario.ServiceReference1.WebService1Soap.EliminarAuto(Concesionario.ServiceReference1.EliminarAutoRequest request) {
            return base.Channel.EliminarAuto(request);
        }
        
        public string EliminarAuto(string placa) {
            Concesionario.ServiceReference1.EliminarAutoRequest inValue = new Concesionario.ServiceReference1.EliminarAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.EliminarAutoRequestBody();
            inValue.Body.placa = placa;
            Concesionario.ServiceReference1.EliminarAutoResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).EliminarAuto(inValue);
            return retVal.Body.EliminarAutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.EliminarAutoResponse> Concesionario.ServiceReference1.WebService1Soap.EliminarAutoAsync(Concesionario.ServiceReference1.EliminarAutoRequest request) {
            return base.Channel.EliminarAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.EliminarAutoResponse> EliminarAutoAsync(string placa) {
            Concesionario.ServiceReference1.EliminarAutoRequest inValue = new Concesionario.ServiceReference1.EliminarAutoRequest();
            inValue.Body = new Concesionario.ServiceReference1.EliminarAutoRequestBody();
            inValue.Body.placa = placa;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).EliminarAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.HelloWorldResponse Concesionario.ServiceReference1.WebService1Soap.HelloWorld(Concesionario.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Concesionario.ServiceReference1.HelloWorldRequest inValue = new Concesionario.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Concesionario.ServiceReference1.HelloWorldRequestBody();
            Concesionario.ServiceReference1.HelloWorldResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.HelloWorldResponse> Concesionario.ServiceReference1.WebService1Soap.HelloWorldAsync(Concesionario.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Concesionario.ServiceReference1.HelloWorldRequest inValue = new Concesionario.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Concesionario.ServiceReference1.HelloWorldRequestBody();
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.Validar_numeroResponse Concesionario.ServiceReference1.WebService1Soap.Validar_numero(Concesionario.ServiceReference1.Validar_numeroRequest request) {
            return base.Channel.Validar_numero(request);
        }
        
        public bool Validar_numero(string texto) {
            Concesionario.ServiceReference1.Validar_numeroRequest inValue = new Concesionario.ServiceReference1.Validar_numeroRequest();
            inValue.Body = new Concesionario.ServiceReference1.Validar_numeroRequestBody();
            inValue.Body.texto = texto;
            Concesionario.ServiceReference1.Validar_numeroResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).Validar_numero(inValue);
            return retVal.Body.Validar_numeroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.Validar_numeroResponse> Concesionario.ServiceReference1.WebService1Soap.Validar_numeroAsync(Concesionario.ServiceReference1.Validar_numeroRequest request) {
            return base.Channel.Validar_numeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.Validar_numeroResponse> Validar_numeroAsync(string texto) {
            Concesionario.ServiceReference1.Validar_numeroRequest inValue = new Concesionario.ServiceReference1.Validar_numeroRequest();
            inValue.Body = new Concesionario.ServiceReference1.Validar_numeroRequestBody();
            inValue.Body.texto = texto;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).Validar_numeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concesionario.ServiceReference1.FormularioResponse Concesionario.ServiceReference1.WebService1Soap.Formulario(Concesionario.ServiceReference1.FormularioRequest request) {
            return base.Channel.Formulario(request);
        }
        
        public string Formulario(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.FormularioRequest inValue = new Concesionario.ServiceReference1.FormularioRequest();
            inValue.Body = new Concesionario.ServiceReference1.FormularioRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            Concesionario.ServiceReference1.FormularioResponse retVal = ((Concesionario.ServiceReference1.WebService1Soap)(this)).Formulario(inValue);
            return retVal.Body.FormularioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Concesionario.ServiceReference1.FormularioResponse> Concesionario.ServiceReference1.WebService1Soap.FormularioAsync(Concesionario.ServiceReference1.FormularioRequest request) {
            return base.Channel.FormularioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Concesionario.ServiceReference1.FormularioResponse> FormularioAsync(string placa, string marca, string modelo, string color) {
            Concesionario.ServiceReference1.FormularioRequest inValue = new Concesionario.ServiceReference1.FormularioRequest();
            inValue.Body = new Concesionario.ServiceReference1.FormularioRequestBody();
            inValue.Body.placa = placa;
            inValue.Body.marca = marca;
            inValue.Body.modelo = modelo;
            inValue.Body.color = color;
            return ((Concesionario.ServiceReference1.WebService1Soap)(this)).FormularioAsync(inValue);
        }
    }
}
